# Generated by Django 3.1.5 on 2022-09-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stay_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='confess',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
