# Generated by Django 3.1.5 on 2022-09-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20220930_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='stay_hidden',
            field=models.BooleanField(default=False, help_text='Stay Anonymous'),
        ),
    ]
