# Generated by Django 3.1.5 on 2022-09-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20220930_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=1001),
        ),
    ]
